blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<slug:slug>', views.category, name='category'),
    path('<slug:slug>', views.post, name='post')
]

cv/urls.py
from django.urls import path

from . import views

app_name = 'cv'
urlpatterns = [
    path('', views.index, name='index'),
]

negativeentropy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Django URLs
    path('admin/', admin.site.urls),
    # Custom URLs
    path('', include('pages.urls')),
    path('blog/', include('blog.urls')),
    path('cv/', include('cv.urls')),
    path('portfolio/', include('portfolio.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.index, name='index'),
]

blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class PostCategory(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name = 'Post Category'
        verbose_name_plural = 'Post Categories'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(PostCategory, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(PostCategory, on_delete=models.CASCADE, blank=True)
    slug = models.SlugField(unique=True, blank=True)
    text = models.TextField(blank=True)
    image = models.ImageField(blank=True, upload_to="blog/images/")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)


    def __str__(self):
        return self.title

pages/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models

# Create your models here.
class WebsiteCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name = 'Website Category'
        verbose_name_plural = 'Website Categories'

    def __str__(self):
        return self.name


class Website(models.Model):
    url = models.URLField(max_length=100)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=100, blank=True)
    category = models.ForeignKey(WebsiteCategory, on_delete=models.CASCADE, blank=True)
    image = models.ImageField(max_length=100, blank=True, upload_to="portfolio/images/")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

pages/forms.py
from django import forms

class ContactForm(forms.Form):
    sender  = forms.EmailField(
        label="E-mail:",
        required=True
    )
    
    subject = forms.CharField(
        label="Subject:",
        max_length=255,
        required=True
    )

    message = forms.CharField(
        label="Your message:",
        widget=forms.Textarea,
        required=False
   )

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Post, PostCategory

# Create your views here.
def index(request):
    cats  = PostCategory.objects.all()
    posts = Post.objects.all()

    context = {
        "cats": cats,
        "posts": posts
    }

    return render(request, 'blog/index.html', context)


def category(request, slug):
    cat = get_object_or_404(PostCategory, slug=slug)
    posts = Post.objects.filter(category=cat)

    context = {
        "cat": cat,
        "posts": posts
    }

    return render(request, 'blog/category.html', context)


def post(request, slug):
    post = get_object_or_404(Post, slug=slug)

    context = {
        "post": post
    }

    return render(request, 'blog/post.html', context)

cv/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'cv/index.html')

pages/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import EmailMessage

from .forms import ContactForm

from blog.models import Post
from portfolio.models import Website

# Create your views here.
def home(request):
    posts = Post.objects.all()[:4]
    websites = Website.objects.all()[:4]

    context = {
        "posts": posts,
        "websites": websites
    }

    return render(request, 'pages/home.html', context)


def about(request):
    return render(request, 'pages/about.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            sender  = form.cleaned_data['sender']
            #name    = form.cleaned_data['name']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']

            mail_to = ['a.kotsampaseris@technologic.gr']
            body = (
                'From: %s\n' \
                'Subject: %s\n\n' \
                'Message: %s'
            ) % (sender, subject, message)
            email = EmailMessage(
                subject,
                body,
                sender,
                mail_to,
                reply_to=[sender]
            )

            try:
                email.send()
                messages.success(request, 'Thanks for your message! I will try to reply soon!')
                return redirect('pages:contact')
            except:
                messages.error(request, 'Your message was not sent! Try again later!')
                return redirect('pages:contact')
    else:
        form = ContactForm()

    context = {
        "form": form
    }

    return render(request, 'pages/contact.html', context)

portfolio/views.py
from django.shortcuts import render

from .models import Website, WebsiteCategory

# Create your views here.
def index(request):
    cats = WebsiteCategory.objects.all()
    websites = Website.objects.all()

    context = {
        "cats": cats,
        "websites": websites,
    }

    return render(request, 'portfolio/index.html', context)

blog/templates/blog/category.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">{{cat.name}}</h1>
<div class="row">
{% for post in posts %}
  <div class="col-md-3">
    <div class="post">
      {% if post.image %}
      <div class="post-image">
        <a href="{% url 'blog:post' post.slug %}"><img src="{{ post.image.url }}" alt="{{post.title}}"></a>
      </div>
      {% endif %}
      <h4 class="post-title"><a href="{% url 'blog:post' post.slug %}">{{post.title}}</a></h4>
      <div class="post-meta">
        <span>Category: <a class="post-category" href="#">{{post.category}}</a></span>
        <span>|</span>
        <span>Date: {{post.created_at | date:"d/m/y"}}</span>
      </div>
      <hr>
      <div class="post-text">{{post.text | safe | slice:":170"}}...</div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">Blog</h1>
<div class="row">
{% for post in posts %}
  <div class="col-md-3">
    <div class="post">
      {% if post.image %}
      <div class="post-image">
        <a href="{% url 'blog:post' post.slug %}"><img src="{{ post.image.url }}" alt="{{post.title}}"></a>
      </div>
      {% endif %}
      <h4 class="post-title"><a href="{% url 'blog:post' post.slug %}">{{post.title}}</a></h4>
      <div class="post-meta">
        <span>Category: <a class="post-category" href="{% url 'blog:category' post.category.slug %}">{{post.category}}</a></span>
        <span>|</span>
        <span>Date: {{post.created_at | date:"d/m/y"}}</span>
      </div>
      <hr>
      <div class="post-text">{{post.text | safe | slice:":170"}}...</div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

blog/templates/blog/post.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'blog/css/post.css' %}">
{% endblock %}

{% block slider %}
{% if post.image %}
<img class="d-block w-100" style="height: 90vh" src="{{post.image.url}}" alt="{{post.name}}">
{% endif %}
{% endblock %}

{% block content %}
<h2 class="post-title">{{post.title}}</h2>
<div class="post-meta">
  <span>Category: <a class="post-category" href="{% url 'blog:category' post.category.slug %}">{{post.category}}</a></span>
  <span>|</span>
  <span>Date: {{post.created_at | date:"M d, Y"}}</span>
</div>
<hr>
<div class="post-text">{{post.text | safe}}</div>
{% endblock %}

pages/templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'pages/css/about.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">My Story</h1>
<div class="about-section">
  <h3 class="about-section-header">Early beginnings</h3>
  <p class="about-section-text">
    I grew up in a small seaside town in rural Greece, <strong>Nea Artaki</strong>, mostly playing football in the streets and working with computers, taking them apart and putting them back together <i>(most of the time)</i>... I wasn't a big fan of school, always found that it suppressed creativity and intelligence, and rewarded conformity and homogeneity. My passion at the time was football and I wanted to become a football manager, so I entered the School of Sports Science and Physical Education in the University of Athens. During my studies in Athens, I unexpectedly fell in love with <strong>Physics and Mathematics</strong> and I decided to move to the UK and become a scientist.
  </p>
</div>
<div class="about-section">
  <h3 class="about-section-header">Living in England</h3>
  <p class="about-section-text">
    Life in the north of England was very difficult in the beginning, with the constant rain and the grey skies. For years I was solely focused on my work, and as a result I finished in the top place in every single year of my education. During the second year of my Bachelor's degree, I was working with <strong>Dr. James Christian and Dr. Graham McDonald</strong> on <i>Fresnel diffraction patterns from fractal apertures</i>, and I wrote a computer program that made our calculations <strong><i>400 times faster</i></strong> and accelerated the analysis of the results, which were presented in the <strong>European Optical Society Annual Meeting (EOSAM 2016)</strong> in Berlin. I continued working with Dr. Christian and Dr. McDonald and what started as my Final Project became a series of papers on <strong>Spatiotemporal Solitons</strong> that were published in the <strong>Physical Review A</strong> of the <strong>Americal Physical Society</strong>. Then I took a big chance and decided to work on Particle Physics and I started my Master's degree on <strong>Particle and Mathematical Physics</strong> in the University of Durham, where I had an opportunity to work with <strong>Prof Simon Ross</strong> on <i>the AdS/CFT Correspondence and the Holographic Entanglement Entropy in AdS Spacetimes</i>, where I received the <strong>Winton MSc Prize</strong> for the top place in the Master's.
  </p>
</div>
<div class="about-section">
  <h3 class="about-section-header">Next Chapter</h3>
  <p class="about-section-text">
    Soon I realised that the academic path was not the best choice for me. I came back to Greece and I started working as a <strong>Junior Developer</strong> for <strong>TechnoLogic LTD</strong>, in order to gain real-life work experience and learn how to code professionally, which was much more different from coding on your own leisure. But then I was offered an opportunity to start a <strong>PhD in Quantum Plasmonics</strong> in the <strong>University of Birmingham</strong>, and I returned to England for a few months. However, I kept on working remotely for TechnoLogic LTD, and during that time I was convinced that a career in Programming was a much better choice for me. I am now back in Greece and working to continuously evolve as a programmer and one day to become an entrepreneur.
  </p>
</div>
{% endblock %}

pages/templates/pages/contact.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'pages/css/contact.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">Contact Page</h1>
<div class="row">
  <div class="col-md-6">
    <h3 class="contact-section-header">Contact Info</h3>
    <h4 class="contact-info-name">Antony Kotsampaseris</h4>
    <h5 class="contact-info-tagline">Senior Software Developer @ <a class="contact-info-social-link" href="www.amdocs.com" target="_blank">Amdocs</a></h5>
    <p class="contact-info-message">Feel free to contact me and join me in the following social media. I will be happy to meet you and possibly work with you on your next exciting project! For more information about me, <a class="contact-info-social-link" href="/about/">check here!</a></p>
    <h5>Social Links</h5>
    <div class="contact-info-social">
      <i class="fa fa-at contact-info-social-icon"></i>
      <a class="contact-info-social-link" href="mailto:a.kotsampaseris@gmail.com" target="_blank">a.kotsampaseris@gmail.com</a>
    </div>
    <div class="contact-info-social">
      <i class="fa fa-linkedin-square contact-info-social-icon"></i>
      <a class="contact-info-social-link" href="https://linkedin.com/akotsampaseris" target="_blank">akotsampaseris</a>
    </div>
    <div class="contact-info-social">
      <i class="fa fa-github contact-info-social-icon"></i>
      <a class="contact-info-social-link" href="https://github.com/akotsampaseris" target="_blank">akotsampaseris</a>
    </div>
    <div class="contact-info-social">
      <i class="fa fa-instagram contact-info-social-icon"></i>
      <a class="contact-info-social-link" href="https://instagram.com/a.kotsampaseris" target="_blank">a.kotsampaseris</a>
    </div>
    <a href="{% url 'pages:home' %}"><img src="/media/negativeentropy/images/tne-logo.png" alt="NegativeEntropy" width="200"></a>
  </div>
  <div class="col-md-6">
    <h3 class="contact-section-header">Contact Me</h3>
    <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" name="button" class="btn btn-primary">Send Message</button>
    </form>
  </div>
</div>
{% endblock %}

pages/templates/pages/home.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'pages/css/home.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block slider %}
<div id="carouselExampleIndicators" class="home-carousel carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
    	<img class="d-block w-100" style="height: 90vh;" src="/media/negativeentropy/images/tne-slider-1.png" alt="First slide">
      <div class="slide-overlay">
        <div class="slide-overlay-text">
          <h1 class="slide-header">
            <p class="slide-header-top">Hello there,</p>
            <p class="slide-header-bottom">I'm Antony.</p>
          </h1>
          <p class="slide-text">Find out more about me.<br> And feel free to get in touch.</p>
          <a class="btn slide-btn" href="/contact/">Contact me</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="section">
  <div class="row">
    <div class="col-md-6">
      <h3 class="section-header">Welcome to my Website</h3><br>
      <p class="section-text">My name is Antony Kotsampaseris, I am a <b>Theoretical Phyisicist</b> and a <b>Full-Stack Web Developer</b>. I have published scientific papers in <b>peer-reviewed journals</b>, written code to obtain results presented in <b>international conferences</b>, and been working as a <b>web developer</b> for several years. Visit <a class="section-link" href="/about/">here</a> to learn more about me!</p>
    </div>
    <div class="col-md-6 text-center">
      <a href="{% url 'pages:about' %}">
        <img src="/media/negativeentropy/images/tne-icon-about.png" alt="" width="40%">
      </a>
    </div>
  </div>
</div>
<hr>
<div class="section">
  <div class="row">
    <div class="col-md-6 text-center">
      <a href="{% url 'portfolio:index' %}">
        <img src="/media/negativeentropy/images/tne-icon-portfolio.png" alt="" width="40%">
      </a>
    </div>
    <div class="col-md-6 text-left">
      <h3 class="section-header">Take a look at my work</h3>
      <p class="section-text">The past couple of years I have been developing and designing websites, using technologies like <strong>Django, Laravel, Wordpress</strong> and others. With a lot of hard work, I have evolved a lot as a programmer and I am constantly challenging myself to become even better. You can view some examples of my work <a class="section-link" href="/portfolio/">here</a>!</p>
    </div>
  </div>
</div>
<hr>
<div class="section">
  <div class="row">
    <div class="col-md-6">
      <h3 class="section-header">Check out my CV</h3>
      <p class="section-text align-middle">Along the way, I have studied in several universities and have worked with some amazing people from all around the world. I would be happy to collaborate on your next exciting open-source projects. You can go through my CV <a class="section-link" href="/cv/">here</a> and get more info about my education and my work experience!</p>
    </div>
    <div class="col-md-6 text-center">
      <a href="{% url 'cv:index' %}">
        <img src="/media/negativeentropy/images/tne-icon-cv.png" alt="" width="40%">
      </a>
    </div>
  </div>
</div>

{% if posts %}
<div class="section">
  <h1 class="section-header">Recent Posts</h1>
  <div class="row">
  {% for post in posts %}
    <div class="col-md-3">
      <div class="post">
        {% if post.image %}
        <div class="post-image">
          <a href="{% url 'blog:post' post.slug %}"><img src="{{ post.image.url }}" alt="{{post.title}}"></a>
        </div>
        {% endif %}
        <h4 class="post-title"><a href="{% url 'blog:post' post.slug %}">{{post.title}}</a></h4>
        <div class="post-meta">
          <span>Category: <a class="post-category" href="{% url 'blog:category' post.category.slug %}">{{post.category}}</a></span>
          <span>|</span>
          <span>Date: {{post.created_at | date:"d/m/y"}}</span>
        </div>
        <hr>
        <div class="post-text">{{post.text | safe | slice:":170"}}...</div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}
{% endblock %}

portfolio/templates/portfolio/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'portfolio/css/portfolio.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">My Portfolio</h1>
{% for cat in cats %}
<h3 class="website-category">{{cat.name}}</h3>
<div class="row">
{% for website in websites %}
{% if website.category == cat %}
  <div class="col-sm-3">
    <div class="website">
      {% if website.image %}
      <div class="website-image">
        <a href="{{website.url}}" target="_blank"><img src="{{ website.image.url }}" alt="{{website.title}}"></a>
      </div>
      {% endif %}
      <h4 class="website-title"><a href="{{website.url}}" target="_blank">{{website.title}}</a></h4>
      <p class="website-url"><a href="{{website.url}}" target="_blank">{{website.url}}</a></p>
      {% if website.description %}
      <p class="website-description">{{website.description}}</p>
      {% endif %}
    </div>
  </div>
{% endif %}
{% endfor %}
</div>
<hr>
{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <!-- Meta - Start -->
    <title>NegativeEntropy</title>
    <meta name="author" content="Antony Kotsampaseris">
    <meta name="description" content="Personal website of Antony Kotsampaseris">
    <meta name="keywords" content="negativeentropy, negative, entropy, negative entropy, antony kotsampaseris, antony, kotsampaseris, physics, programming, web development, web, development, developer">
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#000">
    
    <meta property="og:title" content="Antony Kotsampaseris, MSc" />
    <meta property="og:description" content="Personal website of Antony Kotsampaseris, MSc" />
    <meta property="og:url" content="https://negativeentropy.org" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="/media/negativeentropy/images/tne-slider-1.png" />

    <!-- Meta -  End  -->

    <!-- Links - Start -->
    <link rel="icon" href="/media/negativeentropy/images/tne-icon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'negativeentropy/css/main.css' %}">
    {% include 'inc/bootstrap_css.html' %}

    {% block css %}
    {% endblock %}
    <!-- Links -  End  -->
  </head>
  <body class="bg-dark text-white">
    <div class="content wrapper bg-dark">
      <!-- NavBar - Start -->
      {% include 'inc/nav.html' %}
      <!-- NavBar -  End  -->

      <!-- Slider - Start -->
      {% block slider %}
      {% endblock %}
      <!-- Slider -  End  -->

      <!-- Main Content - Start -->
      <main role="main" class="container p-4" style="margin-bottom: 100px; min-height: 80vh;">
        <!-- Alerts - Start -->
        {% include 'inc/alerts.html' %}
        <!--Alerts -  End  -->

        {% block content %}
        Put content here!
        {% endblock %}
      </main>
      <!-- Main Content -  End  -->

      <!-- Footer - Start -->
      {% include 'inc/footer.html' %}
      <!-- Footer -  End  -->

      <!-- Optional JavaScript - Start -->
      {% include 'inc/bootstrap_js.html' %}
      <!-- Optional JavaScript -  End  -->
    </div>
  </body>
</html>

templates/inc/alerts.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

templates/inc/bootstrap_css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!--<link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.min.css" crossorigin="anonymous">-->

templates/inc/bootstrap_js.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/inc/footer.html
<footer class="footer" style="background-color: #1d1d1d;">
  <div class="container">
    <div class="row" style="padding-top: 30px; padding-bottom: 20px;">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <div class="footer-logo mx-auto" style="text-align: center;">
          <a href="{% url 'pages:home' %}">
            <img src="/media/negativeentropy/images/tne-logo.png" alt="NegativeEntropy" width="200">
          </a>
        </div>
        <div class="social-links" style="text-align: center;">
          <span>
            <a href="https://linkedin.com/akotsampaseris">
              <i class="fa fa-linkedin-square social-icon" style="font-size: 24px; color: #fff;"></i>
            </a>
          </span>
          <span>
            <a href="https://github.com/thenegativeentropy">
              <i class="fa fa-github social-icon" style="font-size: 24px; color: #fff;"></i>
            </a>
          </span>
          <span>
            <a href="https://instagram.com/a.kotsampaseris">
              <i class="fa fa-instagram social-icon" style="font-size: 24px; color: #fff;"></i>
            </a>
          </span>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/inc/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" style="background-color: #1d1d1d !important;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'pages:home' %}">
      <img src="/media/negativeentropy/images/tne-logo.png" alt="negativeEntropy" width="200">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="nav-item nav-link text-white" href="{% url 'pages:about' %}">About me</a>
      <!--<a class="nav-item nav-link text-white" href="{% url 'blog:index' %}">Blog</a>-->
      <a class="nav-item nav-link text-white" href="{% url 'portfolio:index' %}">Portfolio</a>
      <a class="nav-item nav-link text-white" href="{% url 'cv:index' %}">CV</a>
      <a class="nav-item nav-link btn ml-auto text-white" style="background-color: #ea1646;" href="{% url 'pages:contact' %}">Contact me</a>
    </div>
  </div>
</nav>